CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    email VARCHAR(32) UNIQUE NOT NULL,
    password VARCHAR(64) NOT NULL,
    admin BOOLEAN DEFAULT FALSE
);

CREATE TABLE invited_users (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    email VARCHAR(32) UNIQUE NOT NULL,
    admin BOOLEAN DEFAULT FALSE,
    token VARCHAR(16) UNIQUE NOT NULL
);

CREATE TABLE courses (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    title VARCHAR(64) NOT NULL,
    admin_id INT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE course_user (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    course_id INT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE lists (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    course_id INT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    description VARCHAR(64) NOT NULL,
    location VARCHAR(16) NOT NULL,
    start TIMESTAMP NOT NULL DEFAULT '2024-01-01 00:00:00',
    interval INT NOT NULL,
    max_slots INT NOT NULL
);

CREATE TABLE reservations (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    list_id INT NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
